create user awp identified by awp;
 GRANT CREATE DIMENSION TO AWP;
 GRANT CREATE TABLE TO AWP;
 GRANT CREATE JOB TO AWP;
 GRANT CREATE TYPE TO AWP;
 GRANT CREATE OPERATOR TO AWP;
 GRANT CREATE VIEW TO AWP;
 GRANT CREATE INDEXTYPE TO AWP;
 GRANT CREATE CLUSTER TO AWP;
 GRANT CREATE PROCEDURE TO AWP;
 GRANT CREATE SESSION TO AWP;
 GRANT CREATE MATERIALIZED VIEW TO AWP;
 GRANT CREATE SEQUENCE TO AWP;
 GRANT DEBUG CONNECT SESSION TO AWP;
 GRANT CREATE TRIGGER TO AWP;
 GRANT CREATE SYNONYM TO AWP;

/*
create workspace and users on this schema
*/
